services:
  node0:
    build: .
    environment:
      - NODE_ID=0
      - PEERS=node1:5001,node2:5002
      - PORT=5000
    ports:
      - "5000:5000"
    networks:
      - kvnet

  node1:
    build: .
    environment:
      - NODE_ID=1
      - PEERS=node0:5000,node2:5002
      - PORT=5001
    ports:
      - "5001:5001"
    networks:
      - kvnet

  node2:
    build: .
    environment:
      - NODE_ID=2
      - PEERS=node0:5000,node1:5001
      - PORT=5002
    ports:
      - "5002:5002"
    networks:
      - kvnet

networks:
  kvnet: